branch-defaults:
  master:
    environment: development
    group_suffix: null
deploy:
  artifact: target/meli-challenge-mutants-0.0.2.jar
global:
  application_name: meli-challenge-mutants
  branch: null
  default_ec2_keyname: spring-boot-app-key
  default_platform: Java 8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
